# 1) Crie um Dockerfile utilizando a imagem chuanwen/cowsay.
FROM chuanwen/cowsay

# 2) Defina um ENTRYPOINT para a execução do comando.
ENTRYPOINT [ "/usr/games/cowsay" ]

# 3) Utilize o CMD para definir uma mensagem padrão.
CMD [ "MUUUUh" ]