version: '3.1'
services:
  mysql:
    image: mysql:8.0.23
    container_name: container_associations_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  api:
    container_name: api_associations
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=localhost
      - DB_NAME=associationsNN
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql